--Create table with partitions and buckets
DROP TABLE zipcodes;
CREATE TABLE zipcodes (RecordNumber int, Country string, City string, Zipcode int)
PARTITIONED BY (State STRING)
CLUSTERED BY (Zipcode) INTO 3 BUCKETS
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ',';


LOAD DATA LOCAL INPATH '/root/zipcodes.csv' INTO TABLE zipcodes;

INSERT OVERWRITE LOCAL DIRECTORY '/root/HiveOutput3'
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
SELECT * FROM zipcodes WHERE State='PR' AND Zipcode=704;
