services:
  #redis database
    redis-server:
        image: 'redis'
        command: ["redis-server", "--protected-mode", "no"]
        #Node application
    node-app:
        build: ./
        image: docker.io/amruta2025/visits
        ports:
            - "8081:8081"